apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: gaire-platform
    theme: dark
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
  services.yaml: |
    - Lab:
        - Memos:
            href: https://memos.gairelab.uk
            description: Notes
        - ArgoCD:
            href: https://argocd.gairelab.uk
            description: GitOps
        - Whoami:
            href: https://hello.gairelab.uk
            description: Test app
  bookmarks.yaml: |
    - Docs:
        - GitHub:
            - abbr: GH
              href: https://github.com/rameshgaire/gaire-platform
  # Homepage requires this to allow access via the ingress hostname
  kubernetes.yaml: |
    mode: disabled
