apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: gaire-platform
  services.yaml: |
    - Lab:
        - Memos:
            href: https://memos.gairelab.uk
            description: Notes
        - ArgoCD:
            href: https://argocd.gairelab.uk
            description: GitOps
  widgets.yaml: |
    []
  bookmarks.yaml: |
    []
  docker.yaml: |
    {}
  kubernetes.yaml: |
    {}
