apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anythingllm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:rameshgaire/gaire-platform.git
    targetRevision: main
    path: kubernetes/apps/anythingllm
  destination:
    server: https://kubernetes.default.svc
    namespace: anythingllm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
