apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: n8n
          image: n8nio/n8n:1.123.61
          ports:
            - containerPort: 5678
          env:
            - name: N8N_HOST
              value: "n8n.gairelab.uk"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_PORT
              value: "5678"
            - name: WEBHOOK_URL
              value: "https://n8n.gairelab.uk/"
            - name: N8N_PROXY_HOPS
              value: "1"
            - name: GENERIC_TIMEZONE
              value: "Australia/Sydney"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: DB_SQLITE_POOL_SIZE
              value: "5"
          volumeMounts:
            - name: data
              mountPath: /home/node/.n8n
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: n8n-data
